version: '3.8'
services:
  backend:
    build: ./ai-todo/backend
    container_name: ai-todo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/aitodo
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./ai-todo
    container_name: ai-todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: ai-todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 